FROM debian:buster-slim

RUN apt-get update 

WORKDIR /build-temp

# Copy build scripts into the container and run them

COPY soil/deps-apt.sh /build-temp/soil/deps-apt.sh
RUN soil/deps-apt.sh other-tests

COPY soil/deps-R.sh /build-temp/soil/deps-R.sh
RUN soil/deps-R.sh other-tests

CMD ["sh", "-c", "echo 'hello from oilshell/soil-other-tests buildkit'"]
