FROM debian:buster-slim

RUN apt-get update 

WORKDIR /build-temp

# Copy build scripts file into the container and run them

COPY soil/deps-apt.sh /build-temp/soil/deps-apt.sh
RUN soil/deps-apt.sh dummy

CMD ["sh", "-c", "echo 'hello from oilshell/soil-dummy buildkit'"]
